/*
 * Wallust - Firefox Theme
 * This file is autogenerated.
 */

:root {
    --wallust-background: {background};
    --wallust-foreground: {foreground};
    --wallust-cursor: {cursor};
    --wallust-color0: {color0};
    --wallust-color1: {color1};
    --wallust-color2: {color2};
    --wallust-color3: {color3};
    --wallust-color4: {color4};
    --wallust-color5: {color5};
    --wallust-color6: {color6};
    --wallust-color7: {color7};

    /* --- Browser Colors --- */
    --arrowpanel-background: var(--wallust-color0) !important;
    --arrowpanel-color: var(--wallust-foreground) !important;
    --lwt-accent-color: var(--wallust-background) !important;
    --lwt-text-color: var(--wallust-foreground) !important;
    --toolbar-bgcolor: var(--wallust-background) !important;
    --toolbar-color: var(--wallust-foreground) !important;
    --toolbar-field-background-color: var(--wallust-color0) !important;
    --toolbar-field-color: var(--wallust-foreground) !important;
    --toolbar-field-focus-background-color: var(--wallust-color0) !important;
    --urlbar-popup-url-color: var(--wallust-color4) !important;
}

/* New Tab Page */
@-moz-document url("about:newtab"), url("about:home") {
    body {
        background-color: var(--wallust-background) !important;
        color: var(--wallust-foreground) !important;
    }
}

/* Sidebar */
#sidebar-box {
    background-color: var(--wallust-background) !important;
    color: var(--wallust-foreground) !important;
}

/* Selected Tab */
.tab-background[selected="true"] {
    background-color: var(--wallust-color0) !important;
}
