/*
 * Wallust - ADVANCED Firefox Theme
 * This file is autogenerated.
 */
:root {
    --wallust-background: {background};
    --wallust-foreground: {foreground};
    --wallust-color0: {color0};
    --wallust-color1: {color1};
    --wallust-color2: {color2};
    --wallust-color4: {color4};
    --wallust-color7: {color7};

    /* Main UI Colors */
    --arrowpanel-background: var(--wallust-color0) !important;
    --arrowpanel-color: var(--wallust-foreground) !important;
    --lwt-accent-color: var(--wallust-background) !important;
    --lwt-text-color: var(--wallust-foreground) !important;
    --toolbar-bgcolor: var(--wallust-background) !important;
    --toolbar-color: var(--wallust-foreground) !important;

    /* URL Bar and Search */
    --toolbar-field-background-color: var(--wallust-color0) !important;
    --toolbar-field-color: var(--wallust-foreground) !important;
    --urlbar-popup-url-color: var(--wallust-color2) !important;
    --urlbar-popup-match-color: var(--wallust-color4) !important;

    /* Highlight Color for focused URL bar */
    --toolbar-field-focus-border-color: var(--wallust-color4) !important;
    #urlbar[focused="true"] {
        box-shadow: 0 0 10px var(--wallust-color4), 0 0 0 4px var(--wallust-color4) !important;
    }
}

/* Change background of pop-up menus */
menupopup, .menupopup-arrowscrollbox {
    background-color: var(--wallust-background) !important;
}

/* Color for the active/selected tab */
.tab-background[selected="true"] {
    background-color: var(--wallust-color0) !important;
}
.tab-line[selected="true"] {
    background-color: var(--wallust-color4) !important; /* Highlight line for the active tab */
}

/* Sidebar coloring */
#sidebar-box, #sidebar-header {
    background-color: var(--wallust-color0) !important;
}

/* about: pages */
@-moz-document url-prefix("about:") {
    body {
        background-color: var(--wallust-background) !important;
        color: var(--wallust-foreground) !important;
    }
}
