{ config, pkgs, ... }:

{
  home.username = "jake";
  home.homeDirectory = "/home/jake";
  home.stateVersion = "23.05"; # Adjust this to match your Home Manager version

  #ZSH
  programs.zsh = {
    enable = true;
  };

  #TMUX and VIM
  programs.tmux = {
    enable = true;
    extraConfig = ''
      set -g mouse on
      bind-key S setw synchronize-panes
    '';
  };

  # Install user-specific packages
  home.packages = with pkgs; [
    zsh # Ensure Zsh is included in packages
    yazi
    pulseaudio
    rofi-wayland
    nwg-displays
    slurp
    wl-clipboard
    grim
    libnotify
    sway-contrib.grimshot
    eww
    waybar
    nerd-fonts.jetbrains-mono

  # Common dependencies for scripts used in these kinds of themes
    jq           # For parsing JSON in shell scripts
    playerctl    # For media player controls
    brightnessctl # For screen brightness
    pamixer      # A pulseaudio/pipewire mixer for volume control

    # Add other user-specific packages here
  ];

  programs.vim = {
    enable = true;
    plugins = with pkgs.vimPlugins; [
      gruvbox
    ];
    extraConfig = ''
      " Adds syntax highlighting
      syntax on

      " Color scheme
      colorscheme gruvbox
      set background=dark

      " Enable line numbers
      set number

      " Set cursorline
      set cursorline

      " Show matching parentheses
      set showmatch

      " Toggle paste with F2
      set pastetoggle=<F2>

      " Enable mouse support
      set mouse=a

      " Custom keybinding to exit directory with Q
      nnoremap Q :Rexplore<CR>
      inoremap jj <Esc>
    '';
  };

  # --- CONSOLIDATED HOME MANAGER SESSION VARIABLES ---
  home.sessionVariables = {
    # Since Hyprland config is now embedded, we remove HYPRLAND_CONFIG_PATH
    # Hyprland will use the config generated by Home Manager by default.
    # HYPRLAND_CONFIG_PATH = "${config.home.homeDirectory}/.config/hypr/hyprland.conf"; # REMOVE THIS LINE
    PATH = "${config.home.homeDirectory}/.local/bin:$PATH";
    XDG_DATA_DIRS = "${config.home.homeDirectory}/.nix-profile/share:/run/current-system/sw/share:/usr/local/share:/usr/share";
  };
  # --- END OF CONSOLIDATED HOME MANAGER SESSION VARIABLES ---
  home.pointerCursor = {
    name = "Bibata-Modern-Classic";
    package = pkgs.bibata-cursors;
    size = 24;
    enable = true;
  };

  #Flatpak (xdg.enable should be in home.nix too for user-level xdg config)
  xdg.enable = true;

  # Link dotfiles
  home.file.".zshrc".source = ./dotfiles/.zshrc;
  home.file.".tmux.conf".source = ./dotfiles/.tmux.conf;
  home.file.".config/kitty".source = ./kitty; # Ensure this path exists and contains your Kitty config
  home.file.".local/share/fonts/pac.ttf".source = ./dotfiles/dots/waybar/pac.ttf;
  xdg.configFile."eww".source = ./dotfiles/dots/eww;
  xdg.configFile."waybar".source = ./dotfiles/dots/waybar;
  

  # --- HYPRLAND HOME MANAGER CONFIGURATION ---
  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland; # Still needed to specify the package

    # This is where your entire Hyprland configuration goes!
    extraConfig = ''
      # #######################################################################################
      # AUTOGENERATED HYPR CONFIG.
      # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
      # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
      # #######################################################################################

      # This is an example Hyprland config file.
      # Refer to the wiki for more information.
      # https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

      # Please note not all available settings / options are set here.
      # For a full list, see the wiki

      # You can split this configuration into multiple files
      # Create your files separately and then link them to this file like this:
      # source = ~/.config/hypr/myColors.conf


      ################
      ### MONITORS ###
      ################

      # See https://wiki.hyprland.org/Configuring/Monitors/
      monitor=,preferred,auto,auto
  workspace = "1, monitor:desc:BOE 0x095F";

  # Workspace 2 -> Middle Monitor (Acer)
  workspace = "2, monitor:desc:Acer Technologies XV271U M3 1322131231233";

  # Workspace 3 -> Right Monitor (Stargate)
  workspace = "3, monitor:desc:Stargate Technology M156F01 demoset-1";

      ###################
      ### MY PROGRAMS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/

      # Set programs that you use
      $terminal = kitty
      $fileManager = dolphin
      $menu = rofi-wayland --show drun


      #################
      ### AUTOSTART ###
      #################

      # Autostart necessary processes (like notifications daemons, status bars, etc.)
      # Or execute your favorite apps at launch like this:

      # IMPORTANT: Add your autostart commands here, e.g.:
      exec-once = ${pkgs.swww}/bin/swww-daemon
      exec-once = sleep 2 && swww img /home/jake/Pictures/Wallpapers/Gruvwinter.jpg 
      exec-once = ${pkgs.waybar}/bin/waybar # Launch the new Waybar
      exec-once = ${pkgs.eww}/bin/eww daemon # Start the Eww daemon
      exec-once = sleep 2 && ${pkgs.eww}/bin/eww open dashboard # Open the Eww dashboard after a delay

      #exec-once = waybar &
      exec-once = dunst &
      # exec-once = nm-applet & # Uncomment if you use networkmanager applet
      exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Recommended for some apps


      #############################
      ### ENVIRONMENT VARIABLES ###
      #############################

      # See https://wiki.hyprland.org/Configuring/Environment-variables/

      env = XCURSOR_SIZE,24
      env = HYPRCURSOR_SIZE,24
      # Add other environment variables if needed, e.g., MOZ_ENABLE_WAYLAND, QT_QPA_PLATFORM

      #####################
      ### LOOK AND FEEL ###
      #####################

      # Refer to https://wiki.hyprland.org/Configuring/Variables/

      # https://wiki.hyprland.org/Configuring/Variables/#general
      general {
          gaps_in = 5
          gaps_out = 20

          border_size = 2

          # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
          col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
          col.inactive_border = rgba(595959aa)

          # Set to true enable resizing windows by clicking and dragging on borders and gaps
          resize_on_border = false

          # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
          allow_tearing = false

          layout = dwindle
      }

      # https://wiki.hyprland.org/Configuring/Variables/#decoration
      decoration {
          rounding = 10

          # Change transparency of focused and unfocused windows
          active_opacity = 1.0
          inactive_opacity = 1.0
          # https://wiki.hyprland.org/Configuring/Variables/#blur
          blur {
              enabled = true
              size = 3
              passes = 1

              vibrancy = 0.1696
          }
      }

      # https://wiki.hyprland.org/Configuring/Variables/#animations
      animations {
          enabled = true

          # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

          bezier = myBezier, 0.05, 0.9, 0.1, 1.05

          animation = windows, 1, 7, myBezier
          animation = windowsOut, 1, 7, default, popin 80%
          animation = border, 1, 10, default
          animation = borderangle, 1, 8, default
          animation = fade, 1, 7, default
          animation = workspaces, 1, 6, default
      }

      # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
      dwindle {
          pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
          preserve_split = true # You probably want this
      }

      # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
      master {
          new_status = master
      }

      # https://wiki.hyprland.org/Configuring/Variables/#misc
      misc {
          force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
          disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
          disable_splash_rendering = true;
      }


      #############
      ### INPUT ###
      #############

      # https://wiki.hyprland.org/Configuring/Variables/#input
      input {
          kb_layout = us
          kb_variant =
          kb_model =
          kb_options =
          kb_rules =

          follow_mouse = 1

          sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

          touchpad {
              natural_scroll = false
          }
      }

      # https://wiki.hyprland.org/Configuring/Variables/#gestures
      gestures {
          workspace_swipe = false
      }

      # Example per-device config
      # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
      device {
          name = epic-mouse-v1
          sensitivity = -0.5
      }


      ###################
      ### KEYBINDINGS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/
      $mainMod = SUPER # Sets "Windows" key as main modifier

      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
      bind = LCTRL, Q, exec, $terminal
      bind = $mainMod, C, killactive,
      bind = $mainMod, mouse:274, killactive,
      bind = , Print, exec, grimshot --notify savecopy area
      bind = $mainMod, M, exit,
      bind = $mainMod, E, exec, $fileManager
      bind = $mainMod, V, togglefloating,
      bind = LCTRL SUPER, UP, exec, rofi -show drun
      bind = $mainMod, P, pseudo, # dwindle
      bind = $mainMod, J, togglesplit, # dwindle

      # Move focus with mainMod + arrow keys
      bind = SHIFT ALT_L, h, movefocus, l
      bind = SHIFT ALT_L, l, movefocus, r
      bind = SHIFT ALT_L, j, movefocus, d
      bind = SHIFT ALT_L, k, movefocus, u

      bind = , F1, workspace, 1
      bind = , F2, workspace, 2
      bind = , F3, workspace, 3
      bind = , F4, workspace, 4
      bind = , F5, workspace, 5
      bind = , F6, workspace, 6
      bind = , F7, workspace, 7
      bind = , F8, workspace, 8
      bind = , F9, workspace, 9
      bind = , F10, workspace, 10
      bind = $mainMod, 1, movetoworkspace, 1
      bind = $mainMod, 2, movetoworkspace, 2
      bind = $mainMod, 3, movetoworkspace, 3
      bind = $mainMod, 4, movetoworkspace, 4
      bind = $mainMod, 5, movetoworkspace, 5
      bind = $mainMod, 6, movetoworkspace, 6
      bind = $mainMod, 7, movetoworkspace, 7
      bind = $mainMod, 8, movetoworkspace, 8
      bind = $mainMod, 9, movetoworkspace, 9
      bind = $mainMod, 10, movetoworkspace, 10


      # Example special workspace (scratchpad)
      bind = $mainMod, S, togglespecialworkspace, magic
      bind = $mainMod SHIFT, S, movetoworkspace, special:magic

      # Scroll through existing workspaces with mainMod + scroll
      bind = $mainMod, mouse_down, workspace, e+1
      bind = $mainMod, mouse_up, workspace, e-1

      # Move/resize windows with mainMod + LMB/RMB and dragging
      bindm = $mainMod, mouse:272, movewindow
      bindm = $mainMod, mouse:273, resizewindow

      # Laptop multimedia keys for volume and LCD brightness
      bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
      bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
      bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
      bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
      bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
      bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

      # Requires playerctl
      bindl = , XF86AudioNext, exec, playerctl next
      bindl = , XF86AudioPause, exec, playerctl play-pause
      bindl = , XF86AudioPlay, exec, playerctl play-pause
      bindl = , XF86AudioPrev, exec, playerctl previous

      ##############################
      ### WINDOWS AND WORKSPACES ###
      ##############################

      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
      # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

      # Example windowrule v1
      # windowrule = float, ^(kitty)$

      # Example windowrule v2
      # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

      # Ignore maximize requests from apps. You'll probably like this.
      windowrulev2 = suppressevent maximize, class:.*

      # Fix some dragging issues with XWayland
      windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
    ''; # <--- Closing apostrophe and semicolon for extraConfig
  };
  # --- END OF HYPRLAND HOME MANAGER CONFIGURATION ---
}
