#!/bin/bash
DIR="/home/jake/.config/eww/scripts/run/"
A=$(cat ${DIR}state)
eww="eww"
if [ "$A" == "yes" ]; then
	echo "no" > ${DIR}state
	$eww open sidenav
else
	echo "yes" > ${DIR}state
	$eww close sidenav
fi
