#!/bin/bash
DIR="/home/jake/.config/eww/scripts/ss/"
A=$(cat ${DIR}time_o)
if [ "$A" == "yes" ]; then
	echo "no" > ${DIR}time_o
else
	echo "yes" > ${DIR}time_o
fi
eww update ss_time_o="$(cat ${DIR}time_o)"
