#!/bin/bash
DIR="/home/jake/.config/eww/scripts/ss/"
A=$(cat ${DIR}scrn_o)
if [ "$A" == "yes" ]; then
	echo "no" > ${DIR}scrn_o
else
	echo "yes" > ${DIR}scrn_o
fi
eww update ss_scrn_o="$(cat ${DIR}scrn_o)"
