[package]
name = "top_process_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
# Update to the latest version for the most recent features and fixes
sysinfo = "0.30.13" # Or use a more recent version like "0.36.0"
